### ISSUE TITLE
Reminder page has breaking javascript bug

### ISSUE THREAD

**Issue by FoxxMD** [kristopolous/DRR#158]
The [reminder](http://indycast.net/reminder) page fails to enumerate all of the period options (including custom time) due to an undefined variable. This stops execution which prevents station choices from showing which breaks functionality (can't send an email)

I've tested this one Chrome and Firefox.

From the chrome console:

``` js
Object {minutes: 0, hours: 11}
Object {minutes: 0, hours: 12}
Object {minutes: 0, hours: 11}
Object {minutes: 30, hours: 11}
Object {minutes: 30, hours: 11}
Object {minutes: 60, hours: 11}
Object {minutes: 29, hours: 11}
Object {minutes: 69, hours: 11}
Uncaught TypeError: Cannot read property 'split' of undefined
> (anonymous function)  @   reminder.js:38
```

**Comment by kristopolous** [comment]
ack I remember that ... yes thanks ... it was due to adding the +/- 20 minute feature on march 11. 

So basically there were times when I was listening to something that went over the half hour time guards this was set up to deal with.  

That is say you are listening to a 2 hour show and something is being played at the 58th minute in to the 1hr2 minute mark.  You want this for later ... the old model allowed you to select just the current half hour or hour.  This wouldn't have worked.  So this was a remedy for that.  I'll fix it soon. Thanks.

**Comment by kristopolous** [comment]
thanks for reporting this!
